### PR TITLE
Use a concrete release of singularity for integration test

### LINKED ISSUE #147: Move integration tests to use a concrete release of singularity
https://github.com/filecoin-project/motion/blob/f8707839b881638014610e12ac74b4af4d6a5ea0/integration/test/motionlarity/.env#L1

### PR DESCRIPTION
**Pull request by gammazero**
Fixes #147

Running tests locally works:
```
✔ Volume "motionlarity_motion-singularity-volume"        Created   0.0s
 ✔ Container motionlarity-db-1                            Healthy  0.0s
 ✔ Container motionlarity-singularity_admin_init-1        Exited   0.0s
 ✔ Container motionlarity-singularity_content_provider-1  Started  0.0s
 ✔ Container motionlarity-singularity_deal_pusher-1       Started  0.0s
 ✔ Container motionlarity-singularity_deal_tracker-1      Started  0.0s
 ✔ Container motionlarity-singularity_dataset_worker-1    Started  0.0s
 ✔ Container motionlarity-singularity_api-1               Started  0.0s
✔ Container motionlarity-motion-1                        Started

Run Motion integration tests
MOTION_INTEGRATION_TEST='true' go test . -v --count=1
=== RUN   TestRoundTripPutStatusAndFullStorage
    integration_test.go:43: check existing deals
    integration_test.go:59: clearing boost publish queue
    integration_test.go:68: posting 8MB data into motion
    integration_test.go:75: {16901881-fc9b-48a2-ad19-07df40b8ac70}
    integration_test.go:80: requesting data back while still in source storage
    integration_test.go:92: waiting for singularity to make deals with boost
    integration_test.go:108: waiting for singularity to transfer data to boost
    integration_test.go:124: triggering data publish in boost
    integration_test.go:134: awaiting successful deal publishing
    integration_test.go:153: sleeping for 1 minute to allow cleanup worker to run, and indexing to complete
--- PASS: TestRoundTripPutStatusAndFullStorage (121.68s)
PASS
ok      github.com/filecoin-project/motion/integration/test     122.057s
```

### CODE REVIEW

**Comment by masih** [comment]
Looks like CI is failing to fetch images?

> Error response from daemon: Head "https://ghcr.io/v2/data-preservation-programs/singularityv0.5.0/manifests/latest": denied

**Comment by gammazero** [comment]
OK, got this working. Turns out that the singularity build is not tagging images in ghcr for tagged versions. So, I just use the image tag `:main` which is whatever the latest build in the main branch is. If that is really what we want, then this is all good. If we want to refer to a specific tagged release then we will need to tag singularity images.

**Comment by masih** [comment]
> Turns out that the singularity build is not tagging images in ghcr for tagged versions

Are we sure? Looks like [it does](https://github.com/data-preservation-programs/singularity/pkgs/container/singularity/130284368?tag=v0.5.0).

Looking at [this commit](https://github.com/filecoin-project/motion/pull/151/commits/eff28708c8f3459dd9cf0701ebe6223c022e6b3c) it looks like a `v` is missing in the tag name?

**Comment by gammazero** [comment]
I thought I had tried both with and without "v". Anyhow, the testing with the `v0.5.0` image fails always, and testing with the `:main` image succeeds. I think we need to tag a new Singularity release.

**Comment by masih** [comment]
Interesting... I can't see why this is happening. I'll take a closer look tomorrow to see if i can understand what's happening. 

In the meantime, of course. Please feel free to tag a release.

**Comment by gammazero** [comment]
Tagged a newer singularity release, and used that.  Works.

**Review by masih — APPROVED** [review]

**Pull request merged**
